# Generated by Django 2.2.7 on 2019-11-24 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycustomer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.Merchant'),
        ),
        migrations.AlterField(
            model_name='companycustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
        migrations.AlterField(
            model_name='companycustomer',
            name='points',
            field=models.BigIntegerField(default=0),
        ),
    ]
