# Generated by Django 2.2.7 on 2019-11-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_store_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='store_id',
            new_name='store',
        ),
    ]
