# Generated by Django 2.2.7 on 2019-11-17 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='employee',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
            preserve_default=False,
        ),
    ]
