# Generated by Django 2.2.7 on 2019-11-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20191121_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='company_id',
            new_name='company',
        ),
    ]
