# Generated by Django 2.2.7 on 2019-11-18 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('point_systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=256)),
                ('point_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='point_systems.PointSystem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
